on:
  release:
    types:
    - published
  push:
  pull_request:

jobs:
  print-context:
    runs-on: ubuntu-latest

    steps:
    - run: echo $GIT_CONTEXT
      env:
        GIT_CONTEXT: ${{ toJson(github) }}
